version: "3"

services:
  server:
    build: .
    command: bash -c "./mquery-sru server conf-docker.json"
    volumes:
      - corpora-data:/var/lib/manatee
    networks:
      - redis
    ports:
      - 8989:8989

  worker:
    build: .
    command: bash -c "WORKER_ID=0 ./mquery-sru worker conf-docker.json"
    volumes:
      - corpora-data:/var/lib/manatee
    networks:
      - redis

  redis:
    image: redis:latest
    networks:
      - redis

networks:
  redis: {}

volumes:
  corpora-data: {}